//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto_ISI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Refeicao", Namespace="http://schemas.datacontract.org/2004/07/WcfService3")]
    [System.SerializableAttribute()]
    public partial class Refeicao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaloriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestauranteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calorias {
            get {
                return this.CaloriasField;
            }
            set {
                if ((object.ReferenceEquals(this.CaloriasField, value) != true)) {
                    this.CaloriasField = value;
                    this.RaisePropertyChanged("Calorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantidadeField, value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Restaurante {
            get {
                return this.RestauranteField;
            }
            set {
                if ((object.ReferenceEquals(this.RestauranteField, value) != true)) {
                    this.RestauranteField = value;
                    this.RaisePropertyChanged("Restaurante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calorias", Namespace="http://schemas.datacontract.org/2004/07/WcfService3")]
    [System.SerializableAttribute()]
    public partial class Calorias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double caloriasTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double maisMeioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double maisUmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double menosMeioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double menosUmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double caloriasTotal {
            get {
                return this.caloriasTotalField;
            }
            set {
                if ((this.caloriasTotalField.Equals(value) != true)) {
                    this.caloriasTotalField = value;
                    this.RaisePropertyChanged("caloriasTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maisMeio {
            get {
                return this.maisMeioField;
            }
            set {
                if ((this.maisMeioField.Equals(value) != true)) {
                    this.maisMeioField = value;
                    this.RaisePropertyChanged("maisMeio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double maisUm {
            get {
                return this.maisUmField;
            }
            set {
                if ((this.maisUmField.Equals(value) != true)) {
                    this.maisUmField = value;
                    this.RaisePropertyChanged("maisUm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double menosMeio {
            get {
                return this.menosMeioField;
            }
            set {
                if ((this.menosMeioField.Equals(value) != true)) {
                    this.menosMeioField = value;
                    this.RaisePropertyChanged("menosMeio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double menosUm {
            get {
                return this.menosUmField;
            }
            set {
                if ((this.menosUmField.Equals(value) != true)) {
                    this.menosUmField = value;
                    this.RaisePropertyChanged("menosUm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRefeicoes", ReplyAction="http://tempuri.org/IService1/GetRefeicoesResponse")]
        Projecto_ISI.ServiceReference1.Refeicao[] GetRefeicoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRefeicoes", ReplyAction="http://tempuri.org/IService1/GetRefeicoesResponse")]
        System.Threading.Tasks.Task<Projecto_ISI.ServiceReference1.Refeicao[]> GetRefeicoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRefeicao", ReplyAction="http://tempuri.org/IService1/AddRefeicaoResponse")]
        void AddRefeicao(Projecto_ISI.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddRefeicao", ReplyAction="http://tempuri.org/IService1/AddRefeicaoResponse")]
        System.Threading.Tasks.Task AddRefeicaoAsync(Projecto_ISI.ServiceReference1.Refeicao refeicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculadoraPesoIdeal", ReplyAction="http://tempuri.org/IService1/CalculadoraPesoIdealResponse")]
        double CalculadoraPesoIdeal(string genero, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculadoraPesoIdeal", ReplyAction="http://tempuri.org/IService1/CalculadoraPesoIdealResponse")]
        System.Threading.Tasks.Task<double> CalculadoraPesoIdealAsync(string genero, int altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculadoraCalorias", ReplyAction="http://tempuri.org/IService1/CalculadoraCaloriasResponse")]
        Projecto_ISI.ServiceReference1.Calorias[] CalculadoraCalorias(int idade, string genero, double altura, double peso, string actividade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculadoraCalorias", ReplyAction="http://tempuri.org/IService1/CalculadoraCaloriasResponse")]
        System.Threading.Tasks.Task<Projecto_ISI.ServiceReference1.Calorias[]> CalculadoraCaloriasAsync(int idade, string genero, double altura, double peso, string actividade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Projecto_ISI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Projecto_ISI.ServiceReference1.IService1>, Projecto_ISI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Projecto_ISI.ServiceReference1.Refeicao[] GetRefeicoes() {
            return base.Channel.GetRefeicoes();
        }
        
        public System.Threading.Tasks.Task<Projecto_ISI.ServiceReference1.Refeicao[]> GetRefeicoesAsync() {
            return base.Channel.GetRefeicoesAsync();
        }
        
        public void AddRefeicao(Projecto_ISI.ServiceReference1.Refeicao refeicao) {
            base.Channel.AddRefeicao(refeicao);
        }
        
        public System.Threading.Tasks.Task AddRefeicaoAsync(Projecto_ISI.ServiceReference1.Refeicao refeicao) {
            return base.Channel.AddRefeicaoAsync(refeicao);
        }
        
        public double CalculadoraPesoIdeal(string genero, int altura) {
            return base.Channel.CalculadoraPesoIdeal(genero, altura);
        }
        
        public System.Threading.Tasks.Task<double> CalculadoraPesoIdealAsync(string genero, int altura) {
            return base.Channel.CalculadoraPesoIdealAsync(genero, altura);
        }
        
        public Projecto_ISI.ServiceReference1.Calorias[] CalculadoraCalorias(int idade, string genero, double altura, double peso, string actividade) {
            return base.Channel.CalculadoraCalorias(idade, genero, altura, peso, actividade);
        }
        
        public System.Threading.Tasks.Task<Projecto_ISI.ServiceReference1.Calorias[]> CalculadoraCaloriasAsync(int idade, string genero, double altura, double peso, string actividade) {
            return base.Channel.CalculadoraCaloriasAsync(idade, genero, altura, peso, actividade);
        }
    }
}
